apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledger-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mohit-72/devsecops-dodo.git
    targetRevision: main
    path: task-1-deploy-harden/deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: payments

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true